server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    password: ${ICODE_SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${ICODE_SMTP_EMAIL}
